{% set version = '1.4.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tibble
  version: {{ version|replace("-", "_") }}

source:
  fn: tibble_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tibble_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tibble/tibble_{{ version }}.tar.gz
  sha256: 11670353ff7059a55066dd075d1534d6a27bc5c3583fb9bc291bf750a75c5b17

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-cli
    - r-crayon
    - r-pillar >=1.1.0
    - r-rlang
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-cli
    - r-crayon
    - r-pillar >=1.1.0
    - r-rlang
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('tibble')"  # [not win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
  home: https://github.com/tidyverse/tibble
  license: MIT
  summary: Provides a 'tbl_df' class that offers better checking and printing capabilities than
    traditional data frames.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
